require:
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: true

Metrics/BlockLength:
  Exclude:
    - config/**/*.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
